contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://cubscoutpack449.github.io/"
description: "Information"
title: "Cub Scout Pack 449"
canonifyurls: true
theme: "hyde"